--liquibase formatted sql

--changeset SKRaidun:1

CREATE TABLE Users (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
login VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);

--changeset SKRaidun:2
CREATE TABLE IF NOT EXISTS Locations (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
latitude DECIMAL NOT NULL,
longitude DECIMAL NOT NULL,
user_id INT REFERENCES Users(id)
);

--changeset SKRaidun:3
CREATE TABLE IF NOT EXISTS Sessions (
id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
expires_at TIMESTAMP NOT NULL,
user_id INT REFERENCES Users(id)
);
